# Generated by Django 3.0.8 on 2020-07-04 06:10

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inputs', jsonfield.fields.JSONField()),
                ('fileUpload', models.FileField(blank=True, upload_to='file_uploads')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('workflow', jsonfield.fields.JSONField()),
                ('submitTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
