# Generated by Django 3.0.8 on 2020-07-15 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('workflow', jsonfield.fields.JSONField()),
                ('assignee', models.CharField(default='Not Assigned', max_length=255)),
                ('submitTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
                ('LeftReady', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarningsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcementAction', models.CharField(max_length=255)),
                ('law', models.CharField(max_length=255)),
                ('act', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.State')),
            ],
        ),
        migrations.CreateModel(
            name='SWOForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=255)),
                ('proposal', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.State')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionaireForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=255)),
                ('responses', models.CharField(blank=True, max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.State')),
            ],
        ),
        migrations.CreateModel(
            name='FindingsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.State')),
            ],
        ),
        migrations.CreateModel(
            name='CreateInspectionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectionCategory', models.CharField(max_length=255)),
                ('inspectionType', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('referenceNo', models.CharField(blank=True, max_length=255)),
                ('arrivalDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('TeamDetails', models.CharField(max_length=255)),
                ('workPlaceNo', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.State')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarifications', models.CharField(max_length=255)),
                ('approve', models.BooleanField(default=False)),
                ('officerName', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.State')),
            ],
        ),
    ]
