# Generated by Django 3.0.8 on 2020-07-27 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('state_machine', models.CharField(max_length=255)),
                ('execution_arn', models.CharField(max_length=255)),
                ('current_status', models.CharField(default='None', max_length=255)),
                ('assignee', models.CharField(default='Not Assigned', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_enforcement_action', models.CharField(choices=[('Composition Fine', 'Composition Fine'), ('Warning', 'Warning'), ('Notice', 'Notice')], max_length=20)),
                ('Act', models.CharField(max_length=255)),
                ('Law', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Update_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inspection_Category', models.CharField(max_length=100)),
                ('Inspection_Type', models.CharField(max_length=100)),
                ('Reference', models.CharField(choices=[('Case Management & Investigation', 'Case Management & Investigation'), ('Feedback and Appeal', 'Feedback and Appeal'), ('Incident Reporting', 'Incident Reporting'), ('Inspection & Engagement', 'Inspection & Engagement'), ('Monitoring and Surveillance', 'Monitoring and Surveillance')], max_length=100)),
                ('Reference_No', models.CharField(max_length=100)),
                ('Arrival_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Arrival_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Workplace_No', models.CharField(max_length=100)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
        migrations.CreateModel(
            name='SWO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(max_length=255)),
                ('offenderDetails', models.CharField(max_length=255)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Risk_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(choices=[('Basic', 'Basic'), ('Good', 'Good'), ('Not Applicable', 'Not Applicable'), ('Not Assessed', 'Not Assessed'), ('Unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('Question', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Findings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_A', models.CharField(max_length=255)),
                ('Document_Name', models.CharField(max_length=255)),
                ('Document_type', models.CharField(choices=[('Documents and Photos', 'Documents and Photos'), ('Photos', 'Photos'), ('Supporting Documents', 'Supporting Documents')], max_length=255)),
                ('Section_of_Group', models.CharField(choices=[('Section(A) - 1', 'Section(A) - 1')], max_length=20)),
                ('Description_A', models.CharField(max_length=255)),
                ('finished', models.CharField(blank=True, max_length=255)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ApproveOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Approve', 'Approve'), ('Reassign', 'Reassign')], max_length=255)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Approve', 'Approve'), ('Clarifications', 'Clarifications'), ('Reassign', 'Reassign')], max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('stepStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_process.StepStatus')),
            ],
        ),
    ]
